#!/usr/bin/bash

### VARIABLES



### FUNCTIONS
die() {
  echo "ERROR $*"
  exit 99
}


### MAIN

# get action
case "$1" in
  start|stop|status|logs|logsf)
    action="$1"
    ;;
  *)
    die 'Missing or unknown action'
esac

# get host
host="$2"
[[ -z "$host" ]] && die 'Missing host'
case "$host" in
  jira-test)
    appdir=/usr/services/jira-standalone
    ;;
  *)
    appdir=/srv/jira/app
    ;;
esac

# Decide command to run
case "$action" in
  start|stop)
    cmd="${appdir}/bin/${action}-jira.sh"
    ;;
  status)
    # cmd='test $(ps -efw | grep java | grep jira | wc -l) -eq 1 && echo running || echo stopped'
    cmd='test $(ps -efw | grep java | grep jira | grep -v grep | wc -l) -eq 1 && echo running || echo stopped'
    ;;
  logs)
    cmd="tail ${appdir}/logs/catalina.out"
    ;;
  logsf)
    cmd="tail -f ${appdir}/logs/catalina.out"
    ;;
  off|power|shutdown)
    cmd='shutdown -h now'
    ;;
esac

set -x
ssh "$host" "sudo ${cmd}"
