-- SPACE PERMISSIONS. SPACENAME, PERMISSION TYPE, GROUP NAME, USER NAME
SELECT 'SPACE_NAME','PERM_TYPE','GROUP','USER' FROM DUAL
UNION ALL
SELECT SP.SPACENAME, 
SPM.PERMTYPE, 
COALESCE(GROUP_CONCAT(SPM.PERMGROUPNAME),'') AS 'GROUP', 
COALESCE(GROUP_CONCAT(UM.LOWER_USERNAME),'') AS 'USER'
FROM SPACEPERMISSIONS SPM
JOIN SPACES SP ON SPM.SPACEID = SP.SPACEID
LEFT JOIN user_mapping UM ON SPM.PERMUSERNAME = UM.USER_KEY
GROUP BY SP.SPACEID, SPM.PERMTYPE
INTO OUTFILE '/var/lib/mysql-files/SPACE_PERMS.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';
